config/routes.rb
Rails.application.routes.draw do
  resources :users do
    get :followees, on: :member, path: :following #=> get `/users/1/following`
    get :followers, on: :member
  end
  resources :account_activations, only: :edit
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :followships,         only: [:create, :destroy]

  get    '/signup',  to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'

  root 'static_pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token

  has_many :microposts, dependent: :destroy
  has_many :outfollowships, class_name:  'Followship',
                            foreign_key: :follower_id,
                            dependent:   :destroy
  has_many :followees, through: :outfollowships
  has_many :infollowships, class_name: 'Followship',
                           foreign_key: :followee_id,
                           dependent: :destroy
  has_many :followers, through: :infollowships
  has_secure_password

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, 
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  before_create :create_activation_digest
  before_save   :downcase_email

  class << self
    # Returns the hash digest of the given string.
    def digest( string )
      cost = ActiveModel::SecurePassword.min_cost ? 
        BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create( string, cost: cost )
    end
    
    # Returns a random secure token
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def email_activation_link
    UserMailer.account_activation( self ).deliver_now
  end

  def activate
    update( activated:true, activated_at:Time.zone.now )
  end

  def remember
    self.remember_token = User.new_token
    update_attribute :remember_digest, User.digest( remember_token )
  end
  
  def authenticated?( attribute, token )
    digest = send( "#{attribute}_digest" )
    return false if digest.blank?
    BCrypt::Password.new( digest ) == token
  end
  
  def forget
    update_attribute :remember_digest, nil
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update( reset_digest: User.digest( reset_token ), reset_at: Time.zone.now )
  end

  def email_password_reset_link
    UserMailer.password_reset( self ).deliver_now
  end

  def password_reset_expired?
    reset_at < 2.hours.ago # read as: "reset earlier than 2 hours ago"
  end

  def feed
    Micropost.where( user: followees ).
      or( Micropost.where( user: self ) ).
      order( created_at: :desc )
  end

  def followed?( other_user )
    followees.include? other_user
  end
  alias_method :following?, :followed?

  def followed_by?( other_user )
    followers.include? other_user
  end

  def follow( other_user )
    followees << other_user
  end

  def unfollow( other_user )
    followees.delete other_user
  end

  private
    def downcase_email
      email.downcase!
    end

    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest( activation_token )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:index, :edit, :update, :destroy,
                                           :followees, :followers]
  before_action :authorize_user,    only: [:edit, :update]
  before_action :authorize_admin,   only: :destroy

  def index
    @users = User.where( activated:true ).page( params[:page] )
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new( user_params )
    if @user.save
      @user.email_activation_link
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find params[:id]
    @microposts = @user.microposts.page params[:page]
    redirect_to root_path unless @user.activated?
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    
    if @user.update user_params
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find( params[:id] ).destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end

  # GET /users/1/following
  #   see router and dev't note 3-24-17
  def followees
    @user = User.find params[:id]
    @users = @user.followees.page params[:page]
    @title = 'Following'
    render 'followship'
  end

  def followers
    @user = User.find params[:id]
    @users = @user.followers.page params[:page]
    @title = 'Followers'
    render 'followship'
  end

  private
    def user_params
      params.require( :user ).permit( :name, :email, 
        :password, :password_confirmation )
    end

    def authorize_user
      @user = User.find params[:id]
      redirect_to root_path unless current_user?( @user )
    end
    alias_method :correct_user, :authorize_user

    def authorize_admin
      redirect_to root_path unless current_user.admin?
    end
    alias_method :admin_user, :authorize_admin
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80 )
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for current_user.outfollowships.new, remote: true do |f| %>
  <div><%= hidden_field_tag :followee_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/_form_followship.html.erb
<% unless current_user?( @user ) %>
  <div id="form_followship">
  <% if current_user.following?( @user ) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_info.html.erb
<%# rendered on /static_pages/_home_logged_in %>

<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/users/_stats.html.erb
<div class="stats">
  <a href="<%= followees_user_path( @user ) %>">
    <strong id="followees" class="stat">
      <%= @user.followees.count %> <%# use .size ? %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path( @user ) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %> <%# use .size ? %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for current_user.outfollowships.find_by( followee_id: @user.id ),
             html: { method: :delete },
             remote: true do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
    | <%= link_to_unless current_user?( user ), "delete", user, 
        method: :delete,
        data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel='noopener'>change</a>
    </div>
  </div>
</div>

app/views/users/followship.html.erb
<% provide(:title, @title) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'stats' %>
    </section>
  </aside>

  <div class='col-md-8'>
    <%= render 'form_followship' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3><%= pluralize( @user.microposts.count, 'Micropost') %></h3>
      <ol class='microposts'>
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>